spring:
  application:
    name: ibx-gateway
  config:
    import: optional:configserver:http://host.docker.internal:8888

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/
