spring:
  application:
    name: ibx-eureka-server
  config:
    import: optional:configserver:http://host.docker.internal:8888

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false