spring:
  application:
    name: ibx-eureka-server
  cloud:
    config:
      uri: http://localhost:8888  #where the config-service is running
      fail-fast: true             #the service will not run if it can't reach the config-service

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false