spring:
  application:
    name: ibx-account
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ibx-account

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 4000

jwt:
  secret: ibx-account-secret